# This function loads and combines the TE count tables generated by SQuIRE


readSquire <- function(count.tbls.path, count.table.suffix){
  
  squire.files <- collectFiles(count.tbls.path, count.table.suffix)
  
  df <- data.frame()
  
  for(file in squire.files){
    df <- rbind(df,
                read.csv(file, sep = "\t", stringsAsFactors = FALSE))
  }
  

  df <- df %>% select(TE_ID,
                      Sample,
                      tot_counts) %>%
    spread(Sample, tot_counts) %>%
    mutate(across(everything(), ~replace_na(.x, 0)))
  
  colnames(df)[1] <- "TE"
  
  return(df)
}

translate.squire.ids <- function(squire.cnttbl, trans.map){
  
  squire.cnttbl <- merge(trans.map, 
                         squire.cnttbl, 
                         by.x = "Squire.Annotation", 
                         by.y = "TE",
                         all.y = TRUE)
  

  
  squire.cnttbl <- squire.cnttbl[,c(-1)] 
  
  colnames(squire.cnttbl)[1] <- "TE"
  
  return(squire.cnttbl)
}

squireHandler <- function(tool.information){
  
  squire.cnttbl <- readSquire(tool.information$path, tool.information$file)
  
  if (squire.translation) {
    
    trans.map <- read.csv(tool.information$additional.files, 
                          sep = "\t", 
                          header = T,
                          stringsAsFactors = T)
    
    squire.cnttbl <- translate.squire.ids(squire.cnttbl,
                                          trans.map)
    
    rm(trans.map)
    
  }
  
  squire.cnttbl <-
    squire.cnttbl %>% filter(!(is.na(TE) | duplicated(TE)))
  
  return(squire.cnttbl)
  
}
