# This function loads the counttable generated by TEtranscripts

readTEtranscripts <- function(count.tbl){
  
  require(stringi)
  tetranscripts <- read.csv(file = count.tbl, sep = "\t")
  
  new.colnames <- unlist(lapply(colnames(tetranscripts)[2:length(colnames(tetranscripts))], 
                                function(x) strsplit(x, "[.]")))

  new.colnames <- new.colnames[grep('sample', 
                                    new.colnames)]
  
  if(stri_sub(new.colnames[1], -1) == '_'){
    
    new.colnames <- unlist(lapply(new.colnames, function(x) stri_sub(x, 1, -2)))
  
  }
  
  colnames(tetranscripts)[2:ncol(tetranscripts)] <- new.colnames
  
  
  
  tetranscripts <- tetranscripts %>% 
    filter(!grepl("^ENSMUS", gene.TE) | !grepl("^Nfu", gene.TE)) %>% 
    column_to_rownames("gene.TE") %>% 
    rownames_to_column("TE")
  
  tetranscripts$TE <- sapply(strsplit(tetranscripts$TE, "[:]"), `[`,1)
  
  return(tetranscripts) 
}

tetranscriptsHandler <- function(tool.information){

  tetranscripts.cnttbl <- readTEtranscripts(paste0(tool.information$path,
                                            tool.information$file))
  
  return(tetranscripts.cnttbl)
}

